name: Personal Website

theme: jekyll-theme-cayman

navigation:
  - title: "Home"
    url: "/"
  - title: "Biography"
    url: "/bio"
  - title: "Publications"
    url: "https://carranza-pinedo.github.io/bio"
  - title: "News"
    url: "/news"
